---
title: '2020318'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Sys.setlocale(category = "LC_ALL", locale = "UTF-8")

```{r}
library(readr)
library(googlesheets4)
library(tidyverse)
library(dplyr)
library(lubridate)
```

```{r}
exDataPost80s <- read_csv("https://www.dropbox.com/s/rc6t40gsxduysz6/exDataPost80s.csv?dl=1")
View(exDataPost80s)

hypothesisData <- read_csv("https://www.dropbox.com/s/0etoflih5eqc0bc/hypothesisData.csv?dl=1")
View(hypothesisData)

```

```{r}

vNum1 <- c(-1,5)
vNum2 <- c(2,3)
vNum3 <- c(vNum2, vNum1)
vNum4 <- c(vNum3, vNum1)


```




```{r}

my_age <- `我的年紀`

`我的年紀` <- 20

```

```{r}
library(httr)
library(dplyr)
GET("https://api.github.com/repos/tpemartin/108-2-56-inclass-practice/commits") %>%
  content() %>%
  View()
```

```{r}
library(googlesheets4)
`出席狀況表單網址` <-" https://docs.google.com/spreadsheets/d/1oB-5hj1pO5g8FMpZbA7RgIG8NvCRx6WvLPwvleCEV4Q/edit#gid=987577191"
ss <- as_sheets_id(`出席狀況表單網址`)
homework_sheet <- sheets_read(ss,sheet=1)
```


```{r cars}
summary(cars)
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
